######################################################################
# Automatically generated by qmake (2.01a) ven dic 28 23:30:30 2012
######################################################################

TEMPLATE = app
DESTDIR = bin
DEPENDPATH += . src
INCLUDEPATH += . src

#build
OBJECTS_DIR = build/obj
MOC_DIR = build/moc
RCC_DIR = build/rcc
UI_DIR = build/ui

QT += opengl

LIBS += -lGL -lGLU

# Input
HEADERS += src/Window.h
SOURCES += src/main.cpp src/Window.cpp
