######################################################################
# Automatically generated by qmake (2.01a) ven dic 28 23:30:30 2012
######################################################################

TEMPLATE = app
TARGET = build/Mojo
DEPENDPATH += . src
INCLUDEPATH += . src

QT += opengl

LIBS += -lGL -lGLU

# Input
HEADERS += src/Window.h
SOURCES += src/main.cpp src/Window.cpp
